### PR TITLE
JDF-242 - Integrate qstools documentation to jdf-site

### PR DESCRIPTION
**Pull request by rafabene**

### CODE REVIEW

**Comment by LightGuard** [comment]
I spoke with Rafael about some comments to one of the extensions he wrote, but other than that I'm happy merging this in. Who's doing merging for the site?

**Comment by sgilda** [comment]
I think any of us with admin rights can do this. 
Last thing I saw on IRC was a question from @rafabene asking if @pmuir wanted to review this. :-)

**Comment by LightGuard** [comment]
Alright.

On Tue, Mar 26, 2013 at 2:39 PM, sgilda notifications@github.com wrote:

> I think any of us with admin rights can do this.
> Last thing I saw on IRC was a question from @rafabenehttps://github.com/rafabeneasking if
> @pmuir https://github.com/pmuir wanted to review this. :-)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jboss-jdf/jdf-site/pull/12#issuecomment-15487046
> .

## 

Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by rafabene** [comment]
Just to have it documented:

Indexifier PR: https://github.com/awestruct/awestruct/pull/269
Proposed Maven site awestruct extension: https://github.com/awestruct/awestruct-extensions/issues/14

**Pull request merged**
