### PR TITLE
Add submodule and a few other items to the contributing page

### PR DESCRIPTION
**Pull request by sgilda**

### CODE REVIEW

**Comment by sgilda** [comment]
I didn't realize that. Removed the anchors and changed the links. 
I wasn't able to test because I can't render the HTML from markdown at the moment.

**Comment by rafabene** [comment]
It's fine to merge. I'll do it.

FIY you can use github to check the links because it will render the Markdown as HTML: https://github.com/sgilda/jdf-site/blob/0abd603b6886477ce1ac1c1faa33bcf375668c22/CONTRIBUTING.md

**Comment by sgilda** [comment]
@rafabene : I don't believe the internal links work in GitHub. At least, they don't work with the Quickstart README files. :-)

**Comment by sgilda** [comment]
Actually, I was able to render the HTML and the links don't work. :-(

**Pull request merged**
