### PR TITLE
JDF-378 - Awestruct 0.5.2 migration

### PR DESCRIPTION
**Pull request by rafabene**
The migrated site ir running on http://site-jdf.rhcloud.com/

### CODE REVIEW

**Comment by LightGuard** [comment]
What are we doing with hpricot? I don't see anything in the changes that use it, we should look at refactoring it out anyway and use nokogiri. The Gemfile is also missing bootstrap-sass. 
—

**Comment by rafabene** [comment]
It was used on Lanyrd extension. https://github.com/rafabene/jdf-site/blob/c2c3b689e2792ea3b907ae37034c9c7ec0548acb/_ext/lanyrd.rb#L63

I'll refactor it to use nokogiri and add boostrap-sass (but I didn't understand why we need bootstrap-sass on jdf-site Gemfile once that bootstrap-sass is part of awestruct Gemfile)

**Comment by rafabene** [comment]
Done removing Hpricot and using Nokogiri!

**Comment by LightGuard** [comment]
Think of the Gemfile as the pom.xml file. Right now we have an import (require) but we haven't added it to the Gemfile, so it won't be put into the load path when you execute with bundler. 
—

**Comment by rafabene** [comment]
Thanks for clarifying me. After last commit is this PR good to go ?

**Comment by LightGuard** [comment]
Yep

**Comment by rafabene** [comment]
Merged

**Pull request closed without merging**
